// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Job's resource allocation policy describes when, where, and how compute
/// resources should be allocated for the Job.
public struct AllocationPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Location where compute resources should be allocated for the Job.
  public var location: AllocationPolicy.LocationPolicy? = nil

  /// Describe instances that can be created by this AllocationPolicy.
  /// Only instances[0] is supported now.
  public var instances: [AllocationPolicy.InstancePolicyOrTemplate] = []

  /// Defines the service account for Batch-created VMs. If omitted, the [default
  /// Compute Engine service
  /// account](https://cloud.google.com/compute/docs/access/service-accounts#default_service_account)
  /// is used. Must match the service account specified in any used instance
  /// template configured in the Batch job.
  ///
  /// Includes the following fields:
  ///  * email: The service account's email address. If not set, the default
  ///  Compute Engine service account is used.
  ///  * scopes: Additional OAuth scopes to grant the service account, beyond the
  ///  default cloud-platform scope. (list of strings)
  public var serviceAccount: ServiceAccount? = nil

  /// Custom labels to apply to the job and all the Compute Engine resources
  /// that both are created by this allocation policy and support labels.
  ///
  /// Use labels to group and describe the resources they are applied to. Batch
  /// automatically applies predefined labels and supports multiple `labels`
  /// fields for each job, which each let you apply custom labels to various
  /// resources. Label names that start with "goog-" or "google-" are
  /// reserved for predefined labels. For more information about labels with
  /// Batch, see
  /// [Organize resources using
  /// labels](https://cloud.google.com/batch/docs/organize-resources-using-labels).
  public var labels: [Swift.String: Swift.String] = [:]

  /// The network policy.
  ///
  /// If you define an instance template in the `InstancePolicyOrTemplate` field,
  /// Batch will use the network settings in the instance template instead of
  /// this field.
  public var network: AllocationPolicy.NetworkPolicy? = nil

  /// The placement policy.
  public var placement: AllocationPolicy.PlacementPolicy? = nil

  /// Optional. Tags applied to the VM instances.
  ///
  /// The tags identify valid sources or targets for network firewalls.
  /// Each tag must be 1-63 characters long, and comply with
  /// [RFC1035](https://www.ietf.org/rfc/rfc1035.txt).
  public var tags: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AllocationPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AllocationPolicy().with { $0.location = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let location = CodingKeys(stringValue: "location")
    static let instances = CodingKeys(stringValue: "instances")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let labels = CodingKeys(stringValue: "labels")
    static let network = CodingKeys(stringValue: "network")
    static let placement = CodingKeys(stringValue: "placement")
    static let tags = CodingKeys(stringValue: "tags")

    static let _knownKeys: Set<Swift.String> = [
      "location",
      "instances",
      "serviceAccount",
      "labels",
      "network",
      "placement",
      "tags",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.location = try container.decodeIfPresent(
      AllocationPolicy.LocationPolicy.self, forKey: .location)
    if let value = try container.decodeIfPresent(
      [AllocationPolicy.InstancePolicyOrTemplate].self, forKey: .instances)
    {
      self.instances = value
    }
    self.serviceAccount = try container.decodeIfPresent(
      ServiceAccount.self, forKey: .serviceAccount)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.network = try container.decodeIfPresent(
      AllocationPolicy.NetworkPolicy.self, forKey: .network)
    self.placement = try container.decodeIfPresent(
      AllocationPolicy.PlacementPolicy.self, forKey: .placement)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.location, forKey: .location)
    try container.encode(self.instances, forKey: .instances)
    try container.encodeIfPresent(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.network, forKey: .network)
    try container.encodeIfPresent(self.placement, forKey: .placement)
    try container.encode(self.tags, forKey: .tags)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public struct LocationPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A list of location names that are allowed for the job's VMs formatted
    /// as URLs. Each location can be a region or a zone, but you can only
    /// specify one region or multiple zones in one region per job. For example,
    /// `["regions/us-central1"]` allow VMs in any zones in region
    /// `us-central1`, and `["zones/us-central1-a", "zones/us-central1-c"]`
    /// only allow VMs in zones `us-central1-a` and `us-central1-c`. However,
    /// `["regions/us-central1", "zones/us-central1-a", "zones/us-central1-b",
    /// "zones/us-west1-a"]` causes an error because it contains multiple regions
    /// (`us-central1` and `us-west1`).
    ///
    /// The specified region or zones must be in the same region in
    /// which the job is created starting on the following dates:
    ///
    /// +  For projects that have successfully submitted before
    ///    July 31, 2026 at least one job that uses the
    ///    `allowedLocations[]` field with any region or zones
    ///    outside of the job's location, the changes are starting
    ///    on _June 30, 2027_.
    ///
    /// +  For all other projects, the changes are starting on
    ///    _July 31, 2026_.
    ///
    /// For example, for job `projects/123/locations/us-central1/jobs/jobid`,
    /// the specified region or zones must be in `us-central1`. Using a
    /// different region (e.g. `regions/us-west1`) or a zone not in
    /// `us-central1` (e.g. `zones/us-west1-a`) causes an error.
    public var allowedLocations: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LocationPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LocationPolicy().with { $0.allowedLocations = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let allowedLocations = CodingKeys(stringValue: "allowedLocations")

      static let _knownKeys: Set<Swift.String> = [
        "allowedLocations"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .allowedLocations) {
        self.allowedLocations = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.allowedLocations, forKey: .allowedLocations)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.AllocationPolicy.LocationPolicy"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A new persistent disk or a local ssd.
  /// A VM can only have one local SSD setting but multiple local SSD partitions.
  /// See https://cloud.google.com/compute/docs/disks#pdspecs and
  /// https://cloud.google.com/compute/docs/disks#localssds.
  public struct Disk: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Disk type as shown in `gcloud compute disk-types list`.
    /// For example, local SSD uses type "local-ssd".
    /// Persistent disks and boot disks use "pd-balanced", "pd-extreme", "pd-ssd"
    /// or "pd-standard". If not specified, "pd-standard" will be used as the
    /// default type for non-boot disks, "pd-balanced" will be used as the
    /// default type for boot disks.
    public var type: Swift.String = Swift.String()

    /// Disk size in GB.
    ///
    /// **Non-Boot Disk**:
    /// If the `type` specifies a persistent disk, this field
    /// is ignored if `data_source` is set as `image` or `snapshot`.
    /// If the `type` specifies a local SSD, this field should be a multiple of
    /// 375 GB, otherwise, the final size will be the next greater multiple of
    /// 375 GB.
    ///
    /// **Boot Disk**:
    /// Batch will calculate the boot disk size based on source
    /// image and task requirements if you do not speicify the size.
    /// If both this field and the `boot_disk_mib` field in task spec's
    /// `compute_resource` are defined, Batch will only honor this field.
    /// Also, this field should be no smaller than the source disk's
    /// size when the `data_source` is set as `snapshot` or `image`.
    /// For example, if you set an image as the `data_source` field and the
    /// image's default disk size 30 GB, you can only use this field to make the
    /// disk larger or equal to 30 GB.
    public var sizeGb: Swift.Int64 = Swift.Int64()

    /// Local SSDs are available through both "SCSI" and "NVMe" interfaces.
    /// If not indicated, "NVMe" will be the default one for local ssds.
    /// This field is ignored for persistent disks as the interface is chosen
    /// automatically. See
    /// https://cloud.google.com/compute/docs/disks/persistent-disks#choose_an_interface.
    public var diskInterface: Swift.String = Swift.String()

    /// A data source from which a PD will be created.
    public var dataSource: OneOf_DataSource? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Disk`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Disk().with { $0.image = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let image = CodingKeys(stringValue: "image")
      static let snapshot = CodingKeys(stringValue: "snapshot")
      static let type = CodingKeys(stringValue: "type")
      static let sizeGb = CodingKeys(stringValue: "sizeGb")
      static let diskInterface = CodingKeys(stringValue: "diskInterface")

      static let _knownKeys: Set<Swift.String> = [
        "image",
        "snapshot",
        "type",
        "sizeGb",
        "diskInterface",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
        self.type = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .sizeGb) {
        self.sizeGb = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .diskInterface) {
        self.diskInterface = value
      }

      var dataSource: OneOf_DataSource? = nil
      let dataSourceCheckAndSet = {
        if dataSource != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'dataSource'"))
        }
        dataSource = $0
      }
      if let image = try container.decodeIfPresent(Swift.String.self, forKey: .image) {
        try dataSourceCheckAndSet(.image(image))
      }
      if let snapshot = try container.decodeIfPresent(Swift.String.self, forKey: .snapshot) {
        try dataSourceCheckAndSet(.snapshot(snapshot))
      }
      self.dataSource = dataSource
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.type, forKey: .type)
      try container.encode(self.sizeGb, forKey: .sizeGb)
      try container.encode(self.diskInterface, forKey: .diskInterface)

      if let choice = self.dataSource {
        switch choice {
        case .image(let value):
          try container.encode(value, forKey: .image)
        case .snapshot(let value):
          try container.encode(value, forKey: .snapshot)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// A data source from which a PD will be created.
    public enum OneOf_DataSource: Codable, Equatable, Sendable {
      /// URL for a VM image to use as the data source for this disk.
      /// For example, the following are all valid URLs:
      ///
      /// * Specify the image by its family name:
      /// projects/{project}/global/images/family/{image_family}
      /// * Specify the image version:
      /// projects/{project}/global/images/{image_version}
      ///
      /// You can also use Batch customized image in short names.
      /// The following image values are supported for a boot disk:
      ///
      /// * `batch-debian`: use Batch Debian images.
      /// * `batch-cos`: use Batch Container-Optimized images.
      /// * `batch-hpc-rocky`: use Batch HPC Rocky Linux images.
      case image(Swift.String)
      /// Name of a snapshot used as the data source.
      /// Snapshot is not supported as boot disk now.
      case snapshot(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.AllocationPolicy.Disk"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A new or an existing persistent disk (PD) or a local ssd attached to a VM
  /// instance.
  public struct AttachedDisk: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Device name that the guest operating system will see.
    /// It is used by Runnable.volumes field to mount disks. So please specify
    /// the device_name if you want Batch to help mount the disk, and it should
    /// match the device_name field in volumes.
    public var deviceName: Swift.String = Swift.String()

    public var attached: OneOf_Attached? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AttachedDisk`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AttachedDisk().with { $0.newDisk = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let newDisk = CodingKeys(stringValue: "newDisk")
      static let existingDisk = CodingKeys(stringValue: "existingDisk")
      static let deviceName = CodingKeys(stringValue: "deviceName")

      static let _knownKeys: Set<Swift.String> = [
        "newDisk",
        "existingDisk",
        "deviceName",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .deviceName) {
        self.deviceName = value
      }

      var attached: OneOf_Attached? = nil
      let attachedCheckAndSet = {
        if attached != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'attached'"))
        }
        attached = $0
      }
      if let newDisk = try container.decodeIfPresent(AllocationPolicy.Disk?.self, forKey: .newDisk)
      {
        try attachedCheckAndSet(.newDisk(newDisk))
      }
      if let existingDisk = try container.decodeIfPresent(Swift.String.self, forKey: .existingDisk)
      {
        try attachedCheckAndSet(.existingDisk(existingDisk))
      }
      self.attached = attached
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.deviceName, forKey: .deviceName)

      if let choice = self.attached {
        switch choice {
        case .newDisk(let value):
          try container.encode(value, forKey: .newDisk)
        case .existingDisk(let value):
          try container.encode(value, forKey: .existingDisk)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public enum OneOf_Attached: Codable, Equatable, Sendable {
      indirect case newDisk(AllocationPolicy.Disk?)
      /// Name of an existing PD.
      case existingDisk(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.AllocationPolicy.AttachedDisk"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Accelerator describes Compute Engine accelerators to be attached to the VM.
  public struct Accelerator: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The accelerator type. For example, "nvidia-tesla-t4".
    /// See `gcloud compute accelerator-types list`.
    public var type: Swift.String = Swift.String()

    /// The number of accelerators of this type.
    public var count: Swift.Int64 = Swift.Int64()

    /// Deprecated: please use instances[0].install_gpu_drivers instead.
    @available(*, deprecated)
    public var installGpuDrivers: Swift.Bool = Swift.Bool()

    /// Optional. The NVIDIA GPU driver version that should be installed for this
    /// type.
    ///
    /// You can define the specific driver version such as "470.103.01",
    /// following the driver version requirements in
    /// https://cloud.google.com/compute/docs/gpus/install-drivers-gpu#minimum-driver.
    /// Batch will install the specific accelerator driver if qualified.
    public var driverVersion: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Accelerator`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Accelerator().with { $0.type = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let type = CodingKeys(stringValue: "type")
      static let count = CodingKeys(stringValue: "count")
      static let installGpuDrivers = CodingKeys(stringValue: "installGpuDrivers")
      static let driverVersion = CodingKeys(stringValue: "driverVersion")

      static let _knownKeys: Set<Swift.String> = [
        "type",
        "count",
        "installGpuDrivers",
        "driverVersion",
      ]
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
        self.type = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .count) {
        self.count = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .installGpuDrivers) {
        self.installGpuDrivers = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .driverVersion) {
        self.driverVersion = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.type, forKey: .type)
      try container.encode(self.count, forKey: .count)
      try container.encode(self.installGpuDrivers, forKey: .installGpuDrivers)
      try container.encode(self.driverVersion, forKey: .driverVersion)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.AllocationPolicy.Accelerator"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// InstancePolicy describes an instance type and resources attached to each VM
  /// created by this InstancePolicy.
  public struct InstancePolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The Compute Engine machine type.
    public var machineType: Swift.String = Swift.String()

    /// The minimum CPU platform.
    /// See
    /// https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform.
    public var minCpuPlatform: Swift.String = Swift.String()

    /// The provisioning model.
    public var provisioningModel: AllocationPolicy.ProvisioningModel =
      AllocationPolicy.ProvisioningModel()

    /// The accelerators attached to each VM instance.
    public var accelerators: [AllocationPolicy.Accelerator] = []

    /// Boot disk to be created and attached to each VM by this InstancePolicy.
    /// Boot disk will be deleted when the VM is deleted.
    /// Batch API now only supports booting from image.
    public var bootDisk: AllocationPolicy.Disk? = nil

    /// Non-boot disks to be attached for each VM created by this InstancePolicy.
    /// New disks will be deleted when the VM is deleted.
    /// A non-boot disk is a disk that can be of a device with a
    /// file system or a raw storage drive that is not ready for data
    /// storage and accessing.
    public var disks: [AllocationPolicy.AttachedDisk] = []

    /// Optional. If not specified (default), VMs will consume any applicable
    /// reservation. If "NO_RESERVATION" is specified, VMs will not consume any
    /// reservation. Otherwise, if specified, VMs will consume only the specified
    /// reservation.
    public var reservation: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InstancePolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InstancePolicy().with { $0.machineType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let machineType = CodingKeys(stringValue: "machineType")
      static let minCpuPlatform = CodingKeys(stringValue: "minCpuPlatform")
      static let provisioningModel = CodingKeys(stringValue: "provisioningModel")
      static let accelerators = CodingKeys(stringValue: "accelerators")
      static let bootDisk = CodingKeys(stringValue: "bootDisk")
      static let disks = CodingKeys(stringValue: "disks")
      static let reservation = CodingKeys(stringValue: "reservation")

      static let _knownKeys: Set<Swift.String> = [
        "machineType",
        "minCpuPlatform",
        "provisioningModel",
        "accelerators",
        "bootDisk",
        "disks",
        "reservation",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .machineType) {
        self.machineType = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .minCpuPlatform) {
        self.minCpuPlatform = value
      }
      if let value = try container.decodeIfPresent(
        AllocationPolicy.ProvisioningModel.self, forKey: .provisioningModel)
      {
        self.provisioningModel = value
      }
      if let value = try container.decodeIfPresent(
        [AllocationPolicy.Accelerator].self, forKey: .accelerators)
      {
        self.accelerators = value
      }
      self.bootDisk = try container.decodeIfPresent(AllocationPolicy.Disk.self, forKey: .bootDisk)
      if let value = try container.decodeIfPresent(
        [AllocationPolicy.AttachedDisk].self, forKey: .disks)
      {
        self.disks = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .reservation) {
        self.reservation = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.machineType, forKey: .machineType)
      try container.encode(self.minCpuPlatform, forKey: .minCpuPlatform)
      try container.encode(self.provisioningModel, forKey: .provisioningModel)
      try container.encode(self.accelerators, forKey: .accelerators)
      try container.encodeIfPresent(self.bootDisk, forKey: .bootDisk)
      try container.encode(self.disks, forKey: .disks)
      try container.encode(self.reservation, forKey: .reservation)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.AllocationPolicy.InstancePolicy"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// InstancePolicyOrTemplate lets you define the type of resources to use for
  /// this job either with an InstancePolicy or an instance template.
  /// If undefined, Batch picks the type of VM to use and doesn't include
  /// optional VM resources such as GPUs and extra disks.
  public struct InstancePolicyOrTemplate: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Set this field true if you want Batch to help fetch drivers from a third
    /// party location and install them for GPUs specified in
    /// `policy.accelerators` or `instance_template` on your behalf. Default is
    /// false.
    ///
    /// For Container-Optimized Image cases, Batch will install the
    /// accelerator driver following milestones of
    /// https://cloud.google.com/container-optimized-os/docs/release-notes. For
    /// non Container-Optimized Image cases, following
    /// https://github.com/GoogleCloudPlatform/compute-gpu-installation/blob/main/linux/install_gpu_driver.py.
    public var installGpuDrivers: Swift.Bool = Swift.Bool()

    /// Optional. Set this field true if you want Batch to install Ops Agent on
    /// your behalf. Default is false.
    public var installOpsAgent: Swift.Bool = Swift.Bool()

    /// Optional. Set this field to `true` if you want Batch to block
    /// project-level SSH keys from accessing this job's VMs.  Alternatively, you
    /// can configure the job to specify a VM instance template that blocks
    /// project-level SSH keys. In either case, Batch blocks project-level SSH
    /// keys while creating the VMs for this job.
    ///
    /// Batch allows project-level SSH keys for a job's VMs only if all
    /// the following are true:
    ///
    /// + This field is undefined or set to `false`.
    /// + The job's VM instance template (if any) doesn't block project-level
    ///   SSH keys.
    ///
    /// Notably, you can override this behavior by manually updating a VM to
    /// block or allow project-level SSH keys. For more information about
    /// blocking project-level SSH keys, see the Compute Engine documentation:
    /// https://cloud.google.com/compute/docs/connect/restrict-ssh-keys#block-keys
    public var blockProjectSshKeys: Swift.Bool = Swift.Bool()

    public var policyTemplate: OneOf_PolicyTemplate? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InstancePolicyOrTemplate`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InstancePolicyOrTemplate().with { $0.policy = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let policy = CodingKeys(stringValue: "policy")
      static let instanceTemplate = CodingKeys(stringValue: "instanceTemplate")
      static let installGpuDrivers = CodingKeys(stringValue: "installGpuDrivers")
      static let installOpsAgent = CodingKeys(stringValue: "installOpsAgent")
      static let blockProjectSshKeys = CodingKeys(stringValue: "blockProjectSshKeys")

      static let _knownKeys: Set<Swift.String> = [
        "policy",
        "instanceTemplate",
        "installGpuDrivers",
        "installOpsAgent",
        "blockProjectSshKeys",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .installGpuDrivers) {
        self.installGpuDrivers = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .installOpsAgent) {
        self.installOpsAgent = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .blockProjectSshKeys) {
        self.blockProjectSshKeys = value
      }

      var policyTemplate: OneOf_PolicyTemplate? = nil
      let policyTemplateCheckAndSet = {
        if policyTemplate != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'policyTemplate'"))
        }
        policyTemplate = $0
      }
      if let policy = try container.decodeIfPresent(
        AllocationPolicy.InstancePolicy?.self, forKey: .policy)
      {
        try policyTemplateCheckAndSet(.policy(policy))
      }
      if let instanceTemplate = try container.decodeIfPresent(
        Swift.String.self, forKey: .instanceTemplate)
      {
        try policyTemplateCheckAndSet(.instanceTemplate(instanceTemplate))
      }
      self.policyTemplate = policyTemplate
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.installGpuDrivers, forKey: .installGpuDrivers)
      try container.encode(self.installOpsAgent, forKey: .installOpsAgent)
      try container.encode(self.blockProjectSshKeys, forKey: .blockProjectSshKeys)

      if let choice = self.policyTemplate {
        switch choice {
        case .policy(let value):
          try container.encode(value, forKey: .policy)
        case .instanceTemplate(let value):
          try container.encode(value, forKey: .instanceTemplate)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public enum OneOf_PolicyTemplate: Codable, Equatable, Sendable {
      /// InstancePolicy.
      indirect case policy(AllocationPolicy.InstancePolicy?)
      /// Name of an instance template used to create VMs.
      /// Named the field as 'instance_template' instead of 'template' to avoid
      /// C++ keyword conflict.
      ///
      /// Batch only supports global instance templates from the same project as
      /// the job.
      /// You can specify the global instance template as a full or partial URL.
      case instanceTemplate(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.AllocationPolicy.InstancePolicyOrTemplate"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A network interface.
  public struct NetworkInterface: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The URL of an existing network resource.
    /// You can specify the network as a full or partial URL.
    ///
    /// For example, the following are all valid URLs:
    ///
    /// * https://www.googleapis.com/compute/v1/projects/{project}/global/networks/{network}
    /// * projects/{project}/global/networks/{network}
    /// * global/networks/{network}
    public var network: Swift.String = Swift.String()

    /// The URL of an existing subnetwork resource in the network.
    /// You can specify the subnetwork as a full or partial URL.
    ///
    /// For example, the following are all valid URLs:
    ///
    /// * https://www.googleapis.com/compute/v1/projects/{project}/regions/{region}/subnetworks/{subnetwork}
    /// * projects/{project}/regions/{region}/subnetworks/{subnetwork}
    /// * regions/{region}/subnetworks/{subnetwork}
    public var subnetwork: Swift.String = Swift.String()

    /// Default is false (with an external IP address). Required if
    /// no external public IP address is attached to the VM. If no external
    /// public IP address, additional configuration is required to allow the VM
    /// to access Google Services. See
    /// https://cloud.google.com/vpc/docs/configure-private-google-access and
    /// https://cloud.google.com/nat/docs/gce-example#create-nat for more
    /// information.
    public var noExternalIpAddress: Swift.Bool = Swift.Bool()

    /// Optional. The NIC type of the network interface.
    public var nicType: AllocationPolicy.NetworkInterface.NicType? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `NetworkInterface`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NetworkInterface().with { $0.network = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let network = CodingKeys(stringValue: "network")
      static let subnetwork = CodingKeys(stringValue: "subnetwork")
      static let noExternalIpAddress = CodingKeys(stringValue: "noExternalIpAddress")
      static let nicType = CodingKeys(stringValue: "nicType")

      static let _knownKeys: Set<Swift.String> = [
        "network",
        "subnetwork",
        "noExternalIpAddress",
        "nicType",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
        self.network = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnetwork) {
        self.subnetwork = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .noExternalIpAddress) {
        self.noExternalIpAddress = value
      }
      self.nicType = try container.decodeIfPresent(
        AllocationPolicy.NetworkInterface.NicType.self, forKey: .nicType)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.network, forKey: .network)
      try container.encode(self.subnetwork, forKey: .subnetwork)
      try container.encode(self.noExternalIpAddress, forKey: .noExternalIpAddress)
      try container.encodeIfPresent(self.nicType, forKey: .nicType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Compute Engine VM instance NIC type.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum NicType: Codable, Equatable, Sendable {
      /// No type specified.
      case unspecified
      /// GVNIC
      case gvnic
      /// IRDMA
      case irdma
      /// MRDMA
      case mrdma
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .gvnic: return 1
        case .irdma: return 2
        case .mrdma: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "NIC_TYPE_UNSPECIFIED"
        case .gvnic: return "GVNIC"
        case .irdma: return "IRDMA"
        case .mrdma: return "MRDMA"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NicType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "NIC_TYPE_UNSPECIFIED": self = .unspecified
        case "GVNIC": self = .gvnic
        case "IRDMA": self = .irdma
        case "MRDMA": self = .mrdma
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:NicType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .gvnic
        case 2: self = .irdma
        case 3: self = .mrdma
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("NIC_TYPE_UNSPECIFIED")
        case .gvnic: return try container.encode("GVNIC")
        case .irdma: return try container.encode("IRDMA")
        case .mrdma: return try container.encode("MRDMA")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.AllocationPolicy.NetworkInterface"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// NetworkPolicy describes VM instance network configurations.
  public struct NetworkPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Network configurations.
    public var networkInterfaces: [AllocationPolicy.NetworkInterface] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `NetworkPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NetworkPolicy().with { $0.networkInterfaces = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let networkInterfaces = CodingKeys(stringValue: "networkInterfaces")

      static let _knownKeys: Set<Swift.String> = [
        "networkInterfaces"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [AllocationPolicy.NetworkInterface].self, forKey: .networkInterfaces)
      {
        self.networkInterfaces = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.networkInterfaces, forKey: .networkInterfaces)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.AllocationPolicy.NetworkPolicy"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// PlacementPolicy describes a group placement policy for the VMs controlled
  /// by this AllocationPolicy.
  public struct PlacementPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// UNSPECIFIED vs. COLLOCATED (default UNSPECIFIED). Use COLLOCATED when you
    /// want VMs to be located close to each other for low network latency
    /// between the VMs. No placement policy will be generated when collocation
    /// is UNSPECIFIED.
    public var collocation: Swift.String = Swift.String()

    /// When specified, causes the job to fail if more than max_distance logical
    /// switches are required between VMs. Batch uses the most compact possible
    /// placement of VMs even when max_distance is not specified. An explicit
    /// max_distance makes that level of compactness a strict requirement.
    /// Not yet implemented
    public var maxDistance: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PlacementPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PlacementPolicy().with { $0.collocation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let collocation = CodingKeys(stringValue: "collocation")
      static let maxDistance = CodingKeys(stringValue: "maxDistance")

      static let _knownKeys: Set<Swift.String> = [
        "collocation",
        "maxDistance",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .collocation) {
        self.collocation = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .maxDistance) {
        self.maxDistance = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.collocation, forKey: .collocation)
      try container.encode(self.maxDistance, forKey: .maxDistance)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.AllocationPolicy.PlacementPolicy"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Compute Engine VM instance provisioning model.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ProvisioningModel: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Standard VM.
    case standard
    /// SPOT VM.
    case spot
    /// Preemptible VM (PVM).
    ///
    /// Above SPOT VM is the preferable model for preemptible VM instances: the
    /// old preemptible VM model (indicated by this field) is the older model,
    /// and has been migrated to use the SPOT model as the underlying technology.
    /// This old model will still be supported.
    @available(*, deprecated)
    case preemptible
    /// Bound to the lifecycle of the reservation in which it is provisioned.
    case reservationBound
    /// Instance is provisioned with DWS Flex Start and has limited max run
    /// duration.
    case flexStart
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .standard: return 1
      case .spot: return 2
      case .preemptible: return 3
      case .reservationBound: return 4
      case .flexStart: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PROVISIONING_MODEL_UNSPECIFIED"
      case .standard: return "STANDARD"
      case .spot: return "SPOT"
      case .preemptible: return "PREEMPTIBLE"
      case .reservationBound: return "RESERVATION_BOUND"
      case .flexStart: return "FLEX_START"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ProvisioningModel/unknownStringValue(_:)).
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PROVISIONING_MODEL_UNSPECIFIED": self = .unspecified
      case "STANDARD": self = .standard
      case "SPOT": self = .spot
      case "PREEMPTIBLE": self = .preemptible
      case "RESERVATION_BOUND": self = .reservationBound
      case "FLEX_START": self = .flexStart
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ProvisioningModel/unknownIntValue(_:)).
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .standard
      case 2: self = .spot
      case 3: self = .preemptible
      case 4: self = .reservationBound
      case 5: self = .flexStart
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PROVISIONING_MODEL_UNSPECIFIED")
      case .standard: return try container.encode("STANDARD")
      case .spot: return try container.encode("SPOT")
      case .preemptible: return try container.encode("PREEMPTIBLE")
      case .reservationBound: return try container.encode("RESERVATION_BOUND")
      case .flexStart: return try container.encode("FLEX_START")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.batch.v1.AllocationPolicy"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
