// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Google Batch Service.
/// The service manages user submitted batch jobs and allocates Google Compute
/// Engine VM instances to run the jobs.
///
/// @Snippet(path: "BatchServiceQuickstart")
public final class BatchServiceClient: Clients.BatchServiceProtocol, Sendable {
  let inner: any Clients.BatchServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `BatchServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.BatchServiceStub = try Clients.BatchServiceTransport(options)
    inner = Clients.BatchServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.BatchServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Create a Job.
  ///
  /// @Snippet(path: "BatchService_CreateJob")
  public func createJob(
    request: CreateJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBatchV1.Job {
    try await self.inner.createJob(request: request, options: options)
  }

  /// Get a Job specified by its resource name.
  ///
  /// @Snippet(path: "BatchService_GetJob")
  public func getJob(
    request: GetJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBatchV1.Job {
    try await self.inner.getJob(request: request, options: options)
  }

  /// Delete a Job.
  ///
  /// @Snippet(path: "BatchService_DeleteJob")
  public func deleteJob(
    request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteJob(request: request, options: options)
  }

  /// Delete a Job.
  ///
  /// @Snippet(path: "BatchService_DeleteJob")
  public func deleteJob(
    withPolling: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteJob(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Cancel a Job.
  ///
  /// @Snippet(path: "BatchService_CancelJob")
  public func cancelJob(
    request: CancelJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.cancelJob(request: request, options: options)
  }

  /// Cancel a Job.
  ///
  /// @Snippet(path: "BatchService_CancelJob")
  public func cancelJob(
    withPolling: CancelJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<CancelJobResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<CancelJobResponse>.State in
      return try op._extractStatus(CancelJobResponse.self)
    }
    let rawOp = try await self.cancelJob(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<CancelJobResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// List all Jobs for a project within a region.
  ///
  /// @Snippet(path: "BatchService_ListJobs")
  public func listJobs(
    request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBatchV1.ListJobsResponse {
    try await self.inner.listJobs(request: request, options: options)
  }

  /// List all Jobs for a project within a region.
  ///
  /// @Snippet(path: "BatchService_ListJobs")
  public func listJobs(
    byItem: ListJobsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Job, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudBatchV1.ListJobsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listJobs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Return a single Task.
  ///
  /// @Snippet(path: "BatchService_GetTask")
  public func getTask(
    request: GetTaskRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBatchV1.Task {
    try await self.inner.getTask(request: request, options: options)
  }

  /// List Tasks associated with a job.
  ///
  /// @Snippet(path: "BatchService_ListTasks")
  public func listTasks(
    request: ListTasksRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBatchV1.ListTasksResponse {
    try await self.inner.listTasks(request: request, options: options)
  }

  /// List Tasks associated with a job.
  ///
  /// @Snippet(path: "BatchService_ListTasks")
  public func listTasks(
    byItem: ListTasksRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Task, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudBatchV1.ListTasksResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listTasks(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "BatchService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "BatchService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "BatchService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BatchService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BatchService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BatchService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BatchService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BatchService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `BatchServiceClient`.
  ///
  /// To mock `BatchServiceClient` change your functions to receive
  /// `some BatchServiceProtocol` or `any BatchServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol BatchServiceProtocol {
    /// See `BatchServiceClient.createJob`.
    func createJob(request: CreateJobRequest) async throws -> GoogleCloudBatchV1.Job

    /// See `BatchServiceClient.createJob`.
    func createJob(
      parent: Swift.String,
      job: Job?,
      jobId: Swift.String,
    ) async throws -> GoogleCloudBatchV1.Job

    /// See `BatchServiceClient.getJob`.
    func getJob(request: GetJobRequest) async throws -> GoogleCloudBatchV1.Job

    /// See `BatchServiceClient.getJob`.
    func getJob(
      name: Swift.String,
    ) async throws -> GoogleCloudBatchV1.Job

    /// See `BatchServiceClient.deleteJob`.
    func deleteJob(request: DeleteJobRequest) async throws -> GoogleLongRunning.Operation

    /// See `BatchServiceClient.deleteJob`.
    func deleteJob(withPolling: DeleteJobRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `BatchServiceClient.deleteJob`.
    func deleteJob(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `BatchServiceClient.cancelJob`.
    func cancelJob(request: CancelJobRequest) async throws -> GoogleLongRunning.Operation

    /// See `BatchServiceClient.cancelJob`.
    func cancelJob(withPolling: CancelJobRequest) async throws -> any GoogleCloudGax
      .PollableOperation<CancelJobResponse>

    /// See `BatchServiceClient.cancelJob`.
    func cancelJob(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<CancelJobResponse>

    /// See `BatchServiceClient.listJobs`.
    func listJobs(request: ListJobsRequest) async throws -> GoogleCloudBatchV1.ListJobsResponse

    /// See `BatchServiceClient.listJobs`.
    func listJobs(
      byItem: ListJobsRequest
    ) throws -> any AsyncSequence<Job, Swift.Error>

    /// See `BatchServiceClient.listJobs`.
    func listJobs(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Job, Swift.Error>

    /// See `BatchServiceClient.getTask`.
    func getTask(request: GetTaskRequest) async throws -> GoogleCloudBatchV1.Task

    /// See `BatchServiceClient.getTask`.
    func getTask(
      name: Swift.String,
    ) async throws -> GoogleCloudBatchV1.Task

    /// See `BatchServiceClient.listTasks`.
    func listTasks(request: ListTasksRequest) async throws -> GoogleCloudBatchV1.ListTasksResponse

    /// See `BatchServiceClient.listTasks`.
    func listTasks(
      byItem: ListTasksRequest
    ) throws -> any AsyncSequence<Task, Swift.Error>

    /// See `BatchServiceClient.listTasks`.
    func listTasks(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Task, Swift.Error>

    /// See `BatchServiceClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `BatchServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `BatchServiceClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `BatchServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `BatchServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `BatchServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `BatchServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `BatchServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `BatchServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `BatchServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `BatchServiceClient.createJob`.
    func createJob(
      request: CreateJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBatchV1.Job

    /// See `BatchServiceClient.getJob`.
    func getJob(
      request: GetJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBatchV1.Job

    /// See `BatchServiceClient.deleteJob`.
    func deleteJob(
      request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BatchServiceClient.deleteJob`.
    func deleteJob(
      withPolling: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `BatchServiceClient.cancelJob`.
    func cancelJob(
      request: CancelJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BatchServiceClient.cancelJob`.
    func cancelJob(
      withPolling: CancelJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<CancelJobResponse>

    /// See `BatchServiceClient.listJobs`.
    func listJobs(
      request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBatchV1.ListJobsResponse

    /// See `BatchServiceClient.listJobs`.
    func listJobs(
      byItem: ListJobsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Job, Swift.Error>

    /// See `BatchServiceClient.getTask`.
    func getTask(
      request: GetTaskRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBatchV1.Task

    /// See `BatchServiceClient.listTasks`.
    func listTasks(
      request: ListTasksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBatchV1.ListTasksResponse

    /// See `BatchServiceClient.listTasks`.
    func listTasks(
      byItem: ListTasksRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Task, Swift.Error>

    /// See `BatchServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `BatchServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `BatchServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `BatchServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `BatchServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `BatchServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `BatchServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.BatchServiceProtocol {
  public func createJob(request: CreateJobRequest) async throws -> GoogleCloudBatchV1.Job {
    try await self.createJob(request: request, options: .init())
  }

  public func createJob(
    request: CreateJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBatchV1.Job {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createJob(
    parent: Swift.String,
    job: Job?,
    jobId: Swift.String,
  ) async throws -> GoogleCloudBatchV1.Job {
    let request = CreateJobRequest().with {
      $0.parent = parent
      $0.job = job
      $0.jobId = jobId
    }
    return try await self.createJob(request: request)
  }

  public func getJob(request: GetJobRequest) async throws -> GoogleCloudBatchV1.Job {
    try await self.getJob(request: request, options: .init())
  }

  public func getJob(
    request: GetJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBatchV1.Job {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getJob(
    name: Swift.String,
  ) async throws -> GoogleCloudBatchV1.Job {
    let request = GetJobRequest().with {
      $0.name = name
    }
    return try await self.getJob(request: request)
  }

  public func deleteJob(request: DeleteJobRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteJob(request: request, options: .init())
  }

  public func deleteJob(
    request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteJob(withPolling: DeleteJobRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteJob(withPolling: withPolling, options: .init())
  }

  public func deleteJob(
    withPolling: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteJob(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteJobRequest().with {
      $0.name = name
    }
    return try await self.deleteJob(withPolling: request)
  }

  public func cancelJob(request: CancelJobRequest) async throws -> GoogleLongRunning.Operation {
    try await self.cancelJob(request: request, options: .init())
  }

  public func cancelJob(
    request: CancelJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelJob(withPolling: CancelJobRequest) async throws -> any GoogleCloudGax
    .PollableOperation<CancelJobResponse>
  {
    try await self.cancelJob(withPolling: withPolling, options: .init())
  }

  public func cancelJob(
    withPolling: CancelJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<CancelJobResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<CancelJobResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func cancelJob(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<CancelJobResponse> {
    let request = CancelJobRequest().with {
      $0.name = name
    }
    return try await self.cancelJob(withPolling: request)
  }

  public func listJobs(request: ListJobsRequest) async throws -> GoogleCloudBatchV1.ListJobsResponse
  {
    try await self.listJobs(request: request, options: .init())
  }

  public func listJobs(
    request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBatchV1.ListJobsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listJobs(
    byItem: ListJobsRequest
  ) throws -> any AsyncSequence<Job, Swift.Error> {
    try self.listJobs(byItem: byItem, options: .init())
  }

  public func listJobs(
    byItem: ListJobsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Job, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudBatchV1.ListJobsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listJobs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Job, Swift.Error> {
    let request = ListJobsRequest().with {
      $0.parent = parent
    }
    return try self.listJobs(byItem: request)
  }

  public func getTask(request: GetTaskRequest) async throws -> GoogleCloudBatchV1.Task {
    try await self.getTask(request: request, options: .init())
  }

  public func getTask(
    request: GetTaskRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBatchV1.Task {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getTask(
    name: Swift.String,
  ) async throws -> GoogleCloudBatchV1.Task {
    let request = GetTaskRequest().with {
      $0.name = name
    }
    return try await self.getTask(request: request)
  }

  public func listTasks(request: ListTasksRequest) async throws
    -> GoogleCloudBatchV1.ListTasksResponse
  {
    try await self.listTasks(request: request, options: .init())
  }

  public func listTasks(
    request: ListTasksRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBatchV1.ListTasksResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTasks(
    byItem: ListTasksRequest
  ) throws -> any AsyncSequence<Task, Swift.Error> {
    try self.listTasks(byItem: byItem, options: .init())
  }

  public func listTasks(
    byItem: ListTasksRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Task, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudBatchV1.ListTasksResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTasks(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Task, Swift.Error> {
    let request = ListTasksRequest().with {
      $0.parent = parent
    }
    return try self.listTasks(byItem: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
