// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Compute resource requirements.
///
/// ComputeResource defines the amount of resources required for each task.
/// Make sure your tasks have enough resources to successfully run.
/// If you also define the types of resources for a job to use with the
/// [InstancePolicyOrTemplate](https://cloud.google.com/batch/docs/reference/rest/v1/projects.locations.jobs#instancepolicyortemplate)
/// field, make sure both fields are compatible with each other.
public struct ComputeResource: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The milliCPU count.
  ///
  /// `cpuMilli` defines the amount of CPU resources per task in milliCPU units.
  /// For example, `1000` corresponds to 1 vCPU per task. If undefined, the
  /// default value is `2000`.
  ///
  /// If you also define the VM's machine type using the `machineType` in
  /// [InstancePolicy](https://cloud.google.com/batch/docs/reference/rest/v1/projects.locations.jobs#instancepolicy)
  /// field or inside the `instanceTemplate` in the
  /// [InstancePolicyOrTemplate](https://cloud.google.com/batch/docs/reference/rest/v1/projects.locations.jobs#instancepolicyortemplate)
  /// field, make sure the CPU resources for both fields are compatible with each
  /// other and with how many tasks you want to allow to run on the same VM at
  /// the same time.
  ///
  /// For example, if you specify the `n2-standard-2` machine type, which has 2
  /// vCPUs each, you are recommended to set `cpuMilli` no more than `2000`, or
  /// you are recommended to run two tasks on the same VM if you set `cpuMilli`
  /// to `1000` or less.
  public var cpuMilli: Swift.Int64 = Swift.Int64()

  /// Memory in MiB.
  ///
  /// `memoryMib` defines the amount of memory per task in MiB units.
  /// If undefined, the default value is `2000`.
  /// If you also define the VM's machine type using the `machineType` in
  /// [InstancePolicy](https://cloud.google.com/batch/docs/reference/rest/v1/projects.locations.jobs#instancepolicy)
  /// field or inside the `instanceTemplate` in the
  /// [InstancePolicyOrTemplate](https://cloud.google.com/batch/docs/reference/rest/v1/projects.locations.jobs#instancepolicyortemplate)
  /// field, make sure the memory resources for both fields are compatible with
  /// each other and with how many tasks you want to allow to run on the same VM
  /// at the same time.
  ///
  /// For example, if you specify the `n2-standard-2` machine type, which has 8
  /// GiB each, you are recommended to set `memoryMib` to no more than `8192`,
  /// or you are recommended to run two tasks on the same VM if you set
  /// `memoryMib` to `4096` or less.
  public var memoryMib: Swift.Int64 = Swift.Int64()

  /// Extra boot disk size in MiB for each task.
  public var bootDiskMib: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ComputeResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeResource().with { $0.cpuMilli = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cpuMilli = CodingKeys(stringValue: "cpuMilli")
    static let memoryMib = CodingKeys(stringValue: "memoryMib")
    static let bootDiskMib = CodingKeys(stringValue: "bootDiskMib")

    static let _knownKeys: Set<Swift.String> = [
      "cpuMilli",
      "memoryMib",
      "bootDiskMib",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .cpuMilli) {
      self.cpuMilli = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .memoryMib) {
      self.memoryMib = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .bootDiskMib) {
      self.bootDiskMib = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.cpuMilli, forKey: .cpuMilli)
    try container.encode(self.memoryMib, forKey: .memoryMib)
    try container.encode(self.bootDiskMib, forKey: .bootDiskMib)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.batch.v1.ComputeResource"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
