// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// An Environment describes a collection of environment variables to set when
/// executing Tasks.
public struct Environment: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A map of environment variable names to values.
  public var variables: [Swift.String: Swift.String] = [:]

  /// A map of environment variable names to Secret Manager secret names.
  /// The VM will access the named secrets to set the value of each environment
  /// variable.
  public var secretVariables: [Swift.String: Swift.String] = [:]

  /// An encrypted JSON dictionary where the key/value pairs correspond to
  /// environment variable names and their values.
  public var encryptedVariables: Environment.KMSEnvMap? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Environment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Environment().with { $0.variables = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let variables = CodingKeys(stringValue: "variables")
    static let secretVariables = CodingKeys(stringValue: "secretVariables")
    static let encryptedVariables = CodingKeys(stringValue: "encryptedVariables")

    static let _knownKeys: Set<Swift.String> = [
      "variables",
      "secretVariables",
      "encryptedVariables",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .variables)
    {
      self.variables = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .secretVariables)
    {
      self.secretVariables = value
    }
    self.encryptedVariables = try container.decodeIfPresent(
      Environment.KMSEnvMap.self, forKey: .encryptedVariables)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.variables, forKey: .variables)
    try container.encode(self.secretVariables, forKey: .secretVariables)
    try container.encodeIfPresent(self.encryptedVariables, forKey: .encryptedVariables)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public struct KMSEnvMap: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The name of the KMS key that will be used to decrypt the cipher text.
    public var keyName: Swift.String = Swift.String()

    /// The value of the cipherText response from the `encrypt` method.
    public var cipherText: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `KMSEnvMap`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = KMSEnvMap().with { $0.keyName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let keyName = CodingKeys(stringValue: "keyName")
      static let cipherText = CodingKeys(stringValue: "cipherText")

      static let _knownKeys: Set<Swift.String> = [
        "keyName",
        "cipherText",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .keyName) {
        self.keyName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cipherText) {
        self.cipherText = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.keyName, forKey: .keyName)
      try container.encode(self.cipherText, forKey: .cipherText)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.Environment.KMSEnvMap"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.batch.v1.Environment"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
