// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An Environment describes a collection of environment variables to set when
/// executing Tasks.
public struct Environment: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// A map of environment variable names to values.
  public var variables: [Swift.String: Swift.String] = [:]

  /// A map of environment variable names to Secret Manager secret names.
  /// The VM will access the named secrets to set the value of each environment
  /// variable.
  public var secretVariables: [Swift.String: Swift.String] = [:]

  /// An encrypted JSON dictionary where the key/value pairs correspond to
  /// environment variable names and their values.
  public var encryptedVariables: Environment.KMSEnvMap? = nil

  /// Initialize a new instance of `Environment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Environment().with { $0.variables = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public struct KMSEnvMap: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The name of the KMS key that will be used to decrypt the cipher text.
    public var keyName: Swift.String = Swift.String()

    /// The value of the cipherText response from the `encrypt` method.
    public var cipherText: Swift.String = Swift.String()

    /// Initialize a new instance of `KMSEnvMap`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = KMSEnvMap().with { $0.keyName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.Environment.KMSEnvMap"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.batch.v1.Environment"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
