// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The Cloud Batch Job description.
public struct Job: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Job name.
  /// For example: "projects/123456/locations/us-central1/jobs/job01".
  public var name: Swift.String = Swift.String()

  /// Output only. A system generated unique ID for the Job.
  public var uid: Swift.String = Swift.String()

  /// Priority of the Job.
  /// The valid value range is [0, 100). Default value is 0.
  /// Higher value indicates higher priority.
  /// A job with higher priority value is more likely to run earlier if all other
  /// requirements are satisfied.
  public var priority: Swift.Int64 = Swift.Int64()

  /// Required. TaskGroups in the Job. Only one TaskGroup is supported now.
  public var taskGroups: [TaskGroup] = []

  /// Compute resource allocation for all TaskGroups in the Job.
  public var allocationPolicy: AllocationPolicy? = nil

  /// Custom labels to apply to the job and any Cloud Logging
  /// [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry)
  /// that it generates.
  ///
  /// Use labels to group and describe the resources they are applied to. Batch
  /// automatically applies predefined labels and supports multiple `labels`
  /// fields for each job, which each let you apply custom labels to various
  /// resources. Label names that start with "goog-" or "google-" are
  /// reserved for predefined labels. For more information about labels with
  /// Batch, see
  /// [Organize resources using
  /// labels](https://cloud.google.com/batch/docs/organize-resources-using-labels).
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Job status. It is read only for users.
  public var status: JobStatus? = nil

  /// Output only. When the Job was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The last time the Job was updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Log preservation policy for the Job.
  public var logsPolicy: LogsPolicy? = nil

  /// Notification configurations.
  public var notifications: [JobNotification] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Job`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Job().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let priority = CodingKeys(stringValue: "priority")
    static let taskGroups = CodingKeys(stringValue: "taskGroups")
    static let allocationPolicy = CodingKeys(stringValue: "allocationPolicy")
    static let labels = CodingKeys(stringValue: "labels")
    static let status = CodingKeys(stringValue: "status")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let logsPolicy = CodingKeys(stringValue: "logsPolicy")
    static let notifications = CodingKeys(stringValue: "notifications")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "priority",
      "taskGroups",
      "allocationPolicy",
      "labels",
      "status",
      "createTime",
      "updateTime",
      "logsPolicy",
      "notifications",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .priority) {
      self.priority = value
    }
    if let value = try container.decodeIfPresent([TaskGroup].self, forKey: .taskGroups) {
      self.taskGroups = value
    }
    self.allocationPolicy = try container.decodeIfPresent(
      AllocationPolicy.self, forKey: .allocationPolicy)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.status = try container.decodeIfPresent(JobStatus.self, forKey: .status)
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.logsPolicy = try container.decodeIfPresent(LogsPolicy.self, forKey: .logsPolicy)
    if let value = try container.decodeIfPresent([JobNotification].self, forKey: .notifications) {
      self.notifications = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.priority, forKey: .priority)
    try container.encode(self.taskGroups, forKey: .taskGroups)
    try container.encodeIfPresent(self.allocationPolicy, forKey: .allocationPolicy)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.status, forKey: .status)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.logsPolicy, forKey: .logsPolicy)
    try container.encode(self.notifications, forKey: .notifications)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.batch.v1.Job"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
