// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The Cloud Batch Job description.
public struct Job: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Job name.
  /// For example: "projects/123456/locations/us-central1/jobs/job01".
  public var name: Swift.String = Swift.String()

  /// Output only. A system generated unique ID for the Job.
  public var uid: Swift.String = Swift.String()

  /// Priority of the Job.
  /// The valid value range is [0, 100). Default value is 0.
  /// Higher value indicates higher priority.
  /// A job with higher priority value is more likely to run earlier if all other
  /// requirements are satisfied.
  public var priority: Swift.Int64 = Swift.Int64()

  /// Required. TaskGroups in the Job. Only one TaskGroup is supported now.
  public var taskGroups: [TaskGroup] = []

  /// Compute resource allocation for all TaskGroups in the Job.
  public var allocationPolicy: AllocationPolicy? = nil

  /// Custom labels to apply to the job and any Cloud Logging
  /// [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry)
  /// that it generates.
  ///
  /// Use labels to group and describe the resources they are applied to. Batch
  /// automatically applies predefined labels and supports multiple `labels`
  /// fields for each job, which each let you apply custom labels to various
  /// resources. Label names that start with "goog-" or "google-" are
  /// reserved for predefined labels. For more information about labels with
  /// Batch, see
  /// [Organize resources using
  /// labels](https://cloud.google.com/batch/docs/organize-resources-using-labels).
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Job status. It is read only for users.
  public var status: JobStatus? = nil

  /// Output only. When the Job was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The last time the Job was updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Log preservation policy for the Job.
  public var logsPolicy: LogsPolicy? = nil

  /// Notification configurations.
  public var notifications: [JobNotification] = []

  /// Initialize a new instance of `Job`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Job().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.cloud.batch.v1.Job" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
