// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Notification configurations.
public struct JobNotification: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The Pub/Sub topic where notifications for the job, like state
  /// changes, will be published. If undefined, no Pub/Sub notifications
  /// are sent for this job.
  ///
  /// Specify the topic using the following format:
  /// `projects/{project}/topics/{topic}`.
  /// Notably, if you want to specify a Pub/Sub topic that is in a
  /// different project than the job, your administrator must grant your
  /// project's Batch service agent permission to publish to that topic.
  ///
  /// For more information about configuring Pub/Sub notifications for
  /// a job, see
  /// https://cloud.google.com/batch/docs/enable-notifications.
  public var pubsubTopic: Swift.String = Swift.String()

  /// The attribute requirements of messages to be sent to this Pub/Sub topic.
  /// Without this field, no message will be sent.
  public var message: JobNotification.Message? = nil

  /// Initialize a new instance of `JobNotification`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JobNotification().with { $0.pubsubTopic = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Message details.
  /// Describe the conditions under which messages will be sent.
  /// If no attribute is defined, no message will be sent by default.
  /// One message should specify either the job or the task level attributes,
  /// but not both. For example,
  /// job level: JOB_STATE_CHANGED and/or a specified new_job_state;
  /// task level: TASK_STATE_CHANGED and/or a specified new_task_state.
  public struct Message: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The message type.
    public var type: JobNotification.Type_ = JobNotification.Type_()

    /// The new job state.
    public var newJobState: JobStatus.State = JobStatus.State()

    /// The new task state.
    public var newTaskState: TaskStatus.State = TaskStatus.State()

    /// Initialize a new instance of `Message`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Message().with { $0.type = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.batch.v1.JobNotification.Message"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The message type.
  public enum Type_: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Notify users that the job state has changed.
    case jobStateChanged
    /// Notify users that the task state has changed.
    case taskStateChanged
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .jobStateChanged: return 1
      case .taskStateChanged: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .jobStateChanged: return "JOB_STATE_CHANGED"
      case .taskStateChanged: return "TASK_STATE_CHANGED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "JOB_STATE_CHANGED": self = .jobStateChanged
      case "TASK_STATE_CHANGED": self = .taskStateChanged
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .jobStateChanged
      case 2: self = .taskStateChanged
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .jobStateChanged: return try container.encode(1)
      case .taskStateChanged: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.batch.v1.JobNotification"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
