// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Job status.
public struct JobStatus: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Job state
  public var state: JobStatus.State = JobStatus.State()

  /// Job status events
  public var statusEvents: [StatusEvent] = []

  /// Aggregated task status for each TaskGroup in the Job.
  /// The map key is TaskGroup ID.
  public var taskGroups: [Swift.String: JobStatus.TaskGroupStatus] = [:]

  /// The duration of time that the Job spent in status RUNNING.
  public var runDuration: GoogleWKT.Duration? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `JobStatus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JobStatus().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let state = CodingKeys(stringValue: "state")
    static let statusEvents = CodingKeys(stringValue: "statusEvents")
    static let taskGroups = CodingKeys(stringValue: "taskGroups")
    static let runDuration = CodingKeys(stringValue: "runDuration")

    static let _knownKeys: Set<Swift.String> = [
      "state",
      "statusEvents",
      "taskGroups",
      "runDuration",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(JobStatus.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent([StatusEvent].self, forKey: .statusEvents) {
      self.statusEvents = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: JobStatus.TaskGroupStatus].self, forKey: .taskGroups)
    {
      self.taskGroups = value
    }
    self.runDuration = try container.decodeIfPresent(GoogleWKT.Duration.self, forKey: .runDuration)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.statusEvents, forKey: .statusEvents)
    try container.encode(self.taskGroups, forKey: .taskGroups)
    try container.encodeIfPresent(self.runDuration, forKey: .runDuration)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// VM instance status.
  public struct InstanceStatus: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The Compute Engine machine type.
    public var machineType: Swift.String = Swift.String()

    /// The VM instance provisioning model.
    public var provisioningModel: AllocationPolicy.ProvisioningModel =
      AllocationPolicy.ProvisioningModel()

    /// The max number of tasks can be assigned to this instance type.
    public var taskPack: Swift.Int64 = Swift.Int64()

    /// The VM boot disk.
    public var bootDisk: AllocationPolicy.Disk? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InstanceStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InstanceStatus().with { $0.machineType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let machineType = CodingKeys(stringValue: "machineType")
      static let provisioningModel = CodingKeys(stringValue: "provisioningModel")
      static let taskPack = CodingKeys(stringValue: "taskPack")
      static let bootDisk = CodingKeys(stringValue: "bootDisk")

      static let _knownKeys: Set<Swift.String> = [
        "machineType",
        "provisioningModel",
        "taskPack",
        "bootDisk",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .machineType) {
        self.machineType = value
      }
      if let value = try container.decodeIfPresent(
        AllocationPolicy.ProvisioningModel.self, forKey: .provisioningModel)
      {
        self.provisioningModel = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .taskPack) {
        self.taskPack = value
      }
      self.bootDisk = try container.decodeIfPresent(AllocationPolicy.Disk.self, forKey: .bootDisk)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.machineType, forKey: .machineType)
      try container.encode(self.provisioningModel, forKey: .provisioningModel)
      try container.encode(self.taskPack, forKey: .taskPack)
      try container.encodeIfPresent(self.bootDisk, forKey: .bootDisk)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.JobStatus.InstanceStatus"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Aggregated task status for a TaskGroup.
  public struct TaskGroupStatus: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Count of task in each state in the TaskGroup.
    /// The map key is task state name.
    public var counts: [Swift.String: Swift.Int64] = [:]

    /// Status of instances allocated for the TaskGroup.
    public var instances: [JobStatus.InstanceStatus] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TaskGroupStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TaskGroupStatus().with { $0.counts = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let counts = CodingKeys(stringValue: "counts")
      static let instances = CodingKeys(stringValue: "instances")

      static let _knownKeys: Set<Swift.String> = [
        "counts",
        "instances",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.Int64].self, forKey: .counts)
      {
        self.counts = value
      }
      if let value = try container.decodeIfPresent(
        [JobStatus.InstanceStatus].self, forKey: .instances)
      {
        self.instances = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.counts, forKey: .counts)
      try container.encode(self.instances, forKey: .instances)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.JobStatus.TaskGroupStatus"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Valid Job states.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Job state unspecified.
    case unspecified
    /// Job is admitted (validated and persisted) and waiting for resources.
    case queued
    /// Job is scheduled to run as soon as resource allocation is ready.
    /// The resource allocation may happen at a later time but with a high
    /// chance to succeed.
    case scheduled
    /// Resource allocation has been successful. At least one Task in the Job is
    /// RUNNING.
    case running
    /// All Tasks in the Job have finished successfully.
    case succeeded
    /// At least one Task in the Job has failed.
    case failed
    /// The Job will be deleted, but has not been deleted yet. Typically this is
    /// because resources used by the Job are still being cleaned up.
    case deletionInProgress
    /// The Job cancellation is in progress, this is because the resources used
    /// by the Job are still being cleaned up.
    case cancellationInProgress
    /// The Job has been cancelled, the task executions were stopped and the
    /// resources were cleaned up.
    case cancelled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .queued: return 1
      case .scheduled: return 2
      case .running: return 3
      case .succeeded: return 4
      case .failed: return 5
      case .deletionInProgress: return 6
      case .cancellationInProgress: return 7
      case .cancelled: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .queued: return "QUEUED"
      case .scheduled: return "SCHEDULED"
      case .running: return "RUNNING"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .deletionInProgress: return "DELETION_IN_PROGRESS"
      case .cancellationInProgress: return "CANCELLATION_IN_PROGRESS"
      case .cancelled: return "CANCELLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "QUEUED": self = .queued
      case "SCHEDULED": self = .scheduled
      case "RUNNING": self = .running
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "DELETION_IN_PROGRESS": self = .deletionInProgress
      case "CANCELLATION_IN_PROGRESS": self = .cancellationInProgress
      case "CANCELLED": self = .cancelled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .queued
      case 2: self = .scheduled
      case 3: self = .running
      case 4: self = .succeeded
      case 5: self = .failed
      case 6: self = .deletionInProgress
      case 7: self = .cancellationInProgress
      case 8: self = .cancelled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .queued: return try container.encode("QUEUED")
      case .scheduled: return try container.encode("SCHEDULED")
      case .running: return try container.encode("RUNNING")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .failed: return try container.encode("FAILED")
      case .deletionInProgress: return try container.encode("DELETION_IN_PROGRESS")
      case .cancellationInProgress: return try container.encode("CANCELLATION_IN_PROGRESS")
      case .cancelled: return try container.encode("CANCELLED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.batch.v1.JobStatus"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
