// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ListTasks Request.
public struct ListTasksRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of a TaskGroup from which Tasks are being requested.
  /// Pattern:
  /// "projects/{project}/locations/{location}/jobs/{job}/taskGroups/{task_group}"
  public var parent: Swift.String = Swift.String()

  /// Task filter, null filter matches all Tasks.
  /// Filter string should be of the format State=TaskStatus.State e.g.
  /// State=RUNNING
  public var filter: Swift.String = Swift.String()

  /// Page size.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Page token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListTasksRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListTasksRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.batch.v1.ListTasksRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
