// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// LogsPolicy describes if and how a job's logs are preserved. Logs include
/// information that is automatically written by the Batch service agent and any
/// information that you configured the job's runnables to write to the `stdout`
/// or `stderr` streams.
public struct LogsPolicy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// If and where logs should be saved.
  public var destination: LogsPolicy.Destination = LogsPolicy.Destination()

  /// When `destination` is set to `PATH`, you must set this field to the path
  /// where you want logs to be saved. This path can point to a local directory
  /// on the VM or (if congifured) a directory under the mount path of any
  /// Cloud Storage bucket, network file system (NFS), or writable persistent
  /// disk that is mounted to the job. For example, if the job has a bucket with
  /// `mountPath` set to `/mnt/disks/my-bucket`, you can write logs to the
  /// root directory of the `remotePath` of that bucket by setting this field to
  /// `/mnt/disks/my-bucket/`.
  public var logsPath: Swift.String = Swift.String()

  /// Optional. When `destination` is set to `CLOUD_LOGGING`, you can optionally
  /// set this field to configure additional settings for Cloud Logging.
  public var cloudLoggingOption: LogsPolicy.CloudLoggingOption? = nil

  /// Initialize a new instance of `LogsPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LogsPolicy().with { $0.destination = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// `CloudLoggingOption` contains additional settings for Cloud Logging logs
  /// generated by Batch job.
  public struct CloudLoggingOption: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Set this field to `true` to change the [monitored resource
    /// type](https://cloud.google.com/monitoring/api/resources) for
    /// Cloud Logging logs generated by this Batch job from
    /// the
    /// [`batch.googleapis.com/Job`](https://cloud.google.com/monitoring/api/resources#tag_batch.googleapis.com/Job)
    /// type to the formerly used
    /// [`generic_task`](https://cloud.google.com/monitoring/api/resources#tag_generic_task)
    /// type.
    public var useGenericTaskMonitoredResource: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `CloudLoggingOption`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CloudLoggingOption().with { $0.useGenericTaskMonitoredResource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.batch.v1.LogsPolicy.CloudLoggingOption"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The destination (if any) for logs.
  public enum Destination: Codable, Equatable, Sendable {
    /// (Default) Logs are not preserved.
    case unspecified
    /// Logs are streamed to Cloud Logging. Optionally, you can configure
    /// additional settings in the `cloudLoggingOption` field.
    case cloudLogging
    /// Logs are saved to the file path specified in the `logsPath` field.
    case path
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cloudLogging: return 1
      case .path: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DESTINATION_UNSPECIFIED"
      case .cloudLogging: return "CLOUD_LOGGING"
      case .path: return "PATH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DESTINATION_UNSPECIFIED": self = .unspecified
      case "CLOUD_LOGGING": self = .cloudLogging
      case "PATH": self = .path
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cloudLogging
      case 2: self = .path
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .cloudLogging: return try container.encode(1)
      case .path: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.batch.v1.LogsPolicy"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
