// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Status event.
public struct StatusEvent: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Type of the event.
  public var type: Swift.String = Swift.String()

  /// Description of the event.
  public var description: Swift.String = Swift.String()

  /// The time this event occurred.
  public var eventTime: GoogleCloudWKT.Timestamp? = nil

  /// Task Execution.
  /// This field is only defined for task-level status events where the task
  /// fails.
  public var taskExecution: TaskExecution? = nil

  /// Task State.
  /// This field is only defined for task-level status events.
  public var taskState: TaskStatus.State = TaskStatus.State()

  /// Initialize a new instance of `StatusEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StatusEvent().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.batch.v1.StatusEvent"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
