// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Status event.
public struct StatusEvent: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Type of the event.
  public var type: Swift.String = Swift.String()

  /// Description of the event.
  public var description: Swift.String = Swift.String()

  /// The time this event occurred.
  public var eventTime: GoogleWKT.Timestamp? = nil

  /// Task Execution.
  /// This field is only defined for task-level status events where the task
  /// fails.
  public var taskExecution: TaskExecution? = nil

  /// Task State.
  /// This field is only defined for task-level status events.
  public var taskState: TaskStatus.State = TaskStatus.State()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StatusEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StatusEvent().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let type = CodingKeys(stringValue: "type")
    static let description = CodingKeys(stringValue: "description")
    static let eventTime = CodingKeys(stringValue: "eventTime")
    static let taskExecution = CodingKeys(stringValue: "taskExecution")
    static let taskState = CodingKeys(stringValue: "taskState")

    static let _knownKeys: Set<Swift.String> = [
      "type",
      "description",
      "eventTime",
      "taskExecution",
      "taskState",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.eventTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .eventTime)
    self.taskExecution = try container.decodeIfPresent(TaskExecution.self, forKey: .taskExecution)
    if let value = try container.decodeIfPresent(TaskStatus.State.self, forKey: .taskState) {
      self.taskState = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.eventTime, forKey: .eventTime)
    try container.encodeIfPresent(self.taskExecution, forKey: .taskExecution)
    try container.encode(self.taskState, forKey: .taskState)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.batch.v1.StatusEvent"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
