// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// This Task Execution field includes detail information for
/// task execution procedures, based on StatusEvent types.
public struct TaskExecution: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The exit code of a finished task.
  ///
  /// If the task succeeded, the exit code will be 0. If the task failed but not
  /// due to the following reasons, the exit code will be 50000.
  ///
  /// Otherwise, it can be from different sources:
  /// * Batch known failures:
  /// https://cloud.google.com/batch/docs/troubleshooting#reserved-exit-codes.
  /// * Batch runnable execution failures; you can rely on Batch logs to further
  /// diagnose: https://cloud.google.com/batch/docs/analyze-job-using-logs. If
  /// there are multiple runnables failures, Batch only exposes the first error.
  public var exitCode: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `TaskExecution`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TaskExecution().with { $0.exitCode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.batch.v1.TaskExecution"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
