// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A TaskGroup defines one or more Tasks that all share the same TaskSpec.
public struct TaskGroup: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. TaskGroup name.
  /// The system generates this field based on parent Job name.
  /// For example:
  /// "projects/123456/locations/us-west1/jobs/job01/taskGroups/group01".
  public var name: Swift.String = Swift.String()

  /// Required. Tasks in the group share the same task spec.
  public var taskSpec: TaskSpec? = nil

  /// Number of Tasks in the TaskGroup.
  /// Default is 1.
  public var taskCount: Swift.Int64 = Swift.Int64()

  /// Max number of tasks that can run in parallel.
  /// Default to min(task_count, parallel tasks per job limit).
  /// See: [Job Limits](https://cloud.google.com/batch/quotas#job_limits).
  /// Field parallelism must be 1 if the scheduling_policy is IN_ORDER.
  public var parallelism: Swift.Int64 = Swift.Int64()

  /// Scheduling policy for Tasks in the TaskGroup.
  /// The default value is AS_SOON_AS_POSSIBLE.
  public var schedulingPolicy: TaskGroup.SchedulingPolicy = TaskGroup.SchedulingPolicy()

  /// An array of environment variable mappings, which are passed to Tasks with
  /// matching indices. If task_environments is used then task_count should
  /// not be specified in the request (and will be ignored). Task count will be
  /// the length of task_environments.
  ///
  /// Tasks get a BATCH_TASK_INDEX and BATCH_TASK_COUNT environment variable, in
  /// addition to any environment variables set in task_environments, specifying
  /// the number of Tasks in the Task's parent TaskGroup, and the specific Task's
  /// index in the TaskGroup (0 through BATCH_TASK_COUNT - 1).
  public var taskEnvironments: [Environment] = []

  /// Max number of tasks that can be run on a VM at the same time.
  /// If not specified, the system will decide a value based on available
  /// compute resources on a VM and task requirements.
  public var taskCountPerNode: Swift.Int64 = Swift.Int64()

  /// When true, Batch will populate a file with a list of all VMs assigned to
  /// the TaskGroup and set the BATCH_HOSTS_FILE environment variable to the path
  /// of that file. Defaults to false. The host file supports up to 1000 VMs.
  public var requireHostsFile: Swift.Bool = Swift.Bool()

  /// When true, Batch will configure SSH to allow passwordless login between
  /// VMs running the Batch tasks in the same TaskGroup.
  public var permissiveSsh: Swift.Bool = Swift.Bool()

  /// Optional. If not set or set to false, Batch uses the root user to execute
  /// runnables. If set to true, Batch runs the runnables using a non-root user.
  /// Currently, the non-root user Batch used is generated by OS Login. For more
  /// information, see [About OS
  /// Login](https://cloud.google.com/compute/docs/oslogin).
  public var runAsNonRoot: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `TaskGroup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TaskGroup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// How Tasks in the TaskGroup should be scheduled relative to each other.
  public enum SchedulingPolicy: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Run Tasks as soon as resources are available.
    ///
    /// Tasks might be executed in parallel depending on parallelism and
    /// task_count values.
    case asSoonAsPossible
    /// Run Tasks sequentially with increased task index.
    case inOrder
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .asSoonAsPossible: return 1
      case .inOrder: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "SCHEDULING_POLICY_UNSPECIFIED"
      case .asSoonAsPossible: return "AS_SOON_AS_POSSIBLE"
      case .inOrder: return "IN_ORDER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "SCHEDULING_POLICY_UNSPECIFIED": self = .unspecified
      case "AS_SOON_AS_POSSIBLE": self = .asSoonAsPossible
      case "IN_ORDER": self = .inOrder
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .asSoonAsPossible
      case 2: self = .inOrder
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .asSoonAsPossible: return try container.encode(1)
      case .inOrder: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.batch.v1.TaskGroup"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
