// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Spec of a task
public struct TaskSpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The sequence of one or more runnables (executable scripts,
  /// executable containers, and/or barriers) for each task in this task group to
  /// run. Each task runs this list of runnables in order. For a task to succeed,
  /// all of its script and container runnables each must meet at least one of
  /// the following conditions:
  ///
  /// + The runnable exited with a zero status.
  /// + The runnable didn't finish, but you enabled its `background` subfield.
  /// + The runnable exited with a non-zero status, but you enabled its
  ///   `ignore_exit_status` subfield.
  public var runnables: [Runnable] = []

  /// ComputeResource requirements.
  public var computeResource: ComputeResource? = nil

  /// Maximum duration the task should run before being automatically retried
  /// (if enabled) or automatically failed. Format the value of this field
  /// as a time limit in seconds followed by `s`&mdash;for example, `3600s`
  /// for 1 hour. The field accepts any value between 0 and the maximum listed
  /// for the `Duration` field type at
  /// https://protobuf.dev/reference/protobuf/google.protobuf/#duration; however,
  /// the actual maximum run time for a job will be limited to the maximum run
  /// time for a job listed at
  /// https://cloud.google.com/batch/quotas#max-job-duration.
  public var maxRunDuration: GoogleCloudWkt.Duration? = nil

  /// Maximum number of retries on failures.
  /// The default, 0, which means never retry.
  /// The valid value range is [0, 10].
  public var maxRetryCount: Swift.Int32 = Swift.Int32()

  /// Lifecycle management schema when any task in a task group is failed.
  /// Currently we only support one lifecycle policy.
  /// When the lifecycle policy condition is met,
  /// the action in the policy will execute.
  /// If task execution result does not meet with the defined lifecycle
  /// policy, we consider it as the default policy.
  /// Default policy means if the exit code is 0, exit task.
  /// If task ends with non-zero exit code, retry the task with max_retry_count.
  public var lifecyclePolicies: [LifecyclePolicy] = []

  /// Deprecated: please use environment(non-plural) instead.
  @available(*, deprecated)
  public var environments: [Swift.String: Swift.String] = [:]

  /// Volumes to mount before running Tasks using this TaskSpec.
  public var volumes: [Volume] = []

  /// Environment variables to set before running the Task.
  public var environment: Environment? = nil

  /// Initialize a new instance of `TaskSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TaskSpec().with { $0.runnables = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.batch.v1.TaskSpec"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
