// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Volume describes a volume and parameters for it to be mounted to a VM.
public struct Volume: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The mount path for the volume, e.g. /mnt/disks/share.
  public var mountPath: Swift.String = Swift.String()

  /// Mount options vary based on the type of storage volume:
  ///
  /// * For a Cloud Storage bucket, all the mount options provided
  /// by
  ///   the [`gcsfuse` tool](https://cloud.google.com/storage/docs/gcsfuse-cli)
  ///   are supported.
  /// * For an existing persistent disk, all mount options provided by the
  ///   [`mount` command](https://man7.org/linux/man-pages/man8/mount.8.html)
  ///   except writing are supported. This is due to restrictions of
  ///   [multi-writer
  ///   mode](https://cloud.google.com/compute/docs/disks/sharing-disks-between-vms).
  /// * For any other disk or a Network File System (NFS), all the
  ///   mount options provided by the `mount` command are supported.
  public var mountOptions: [Swift.String] = []

  /// The source for the volume.
  public var source: OneOf_Source? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Volume`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Volume().with { $0.nfs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let nfs = CodingKeys(stringValue: "nfs")
    static let gcs = CodingKeys(stringValue: "gcs")
    static let deviceName = CodingKeys(stringValue: "deviceName")
    static let mountPath = CodingKeys(stringValue: "mountPath")
    static let mountOptions = CodingKeys(stringValue: "mountOptions")

    static let _knownKeys: Set<Swift.String> = [
      "nfs",
      "gcs",
      "deviceName",
      "mountPath",
      "mountOptions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mountPath) {
      self.mountPath = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .mountOptions) {
      self.mountOptions = value
    }

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let nfs = try container.decodeIfPresent(NFS?.self, forKey: .nfs) {
      try sourceCheckAndSet(.nfs(nfs))
    }
    if let gcs = try container.decodeIfPresent(GCS?.self, forKey: .gcs) {
      try sourceCheckAndSet(.gcs(gcs))
    }
    if let deviceName = try container.decodeIfPresent(Swift.String.self, forKey: .deviceName) {
      try sourceCheckAndSet(.deviceName(deviceName))
    }
    self.source = source
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.mountPath, forKey: .mountPath)
    try container.encode(self.mountOptions, forKey: .mountOptions)

    if let choice = self.source {
      switch choice {
      case .nfs(let value):
        try container.encode(value, forKey: .nfs)
      case .gcs(let value):
        try container.encode(value, forKey: .gcs)
      case .deviceName(let value):
        try container.encode(value, forKey: .deviceName)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The source for the volume.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// A Network File System (NFS) volume. For example, a
    /// Filestore file share.
    indirect case nfs(NFS?)
    /// A Google Cloud Storage (GCS) volume.
    indirect case gcs(GCS?)
    /// Device name of an attached disk volume, which should align with a
    /// device_name specified by
    /// job.allocation_policy.instances[0].policy.disks[i].device_name or
    /// defined by the given instance template in
    /// job.allocation_policy.instances[0].instance_template.
    case deviceName(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.batch.v1.Volume"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
